### ISSUE TITLE
Fixing the emulation of ICCA and Bill Validator on charging machine

### ISSUE THREAD

**Issue by ichijyo-hotaru** [spice2x/spice2x.github.io#123]
## Description of change

Fixing the emulation of ICCA and Bill Validator on charging machine (LA9)

## Testing

I have confirmed the entire process from card recognition to charging and completion.

## Patch file

[patch.txt](https://github.com/spice2x/spice2x.github.io/files/13930111/patch.txt)

**Comment by ichijyo-hotaru** [comment]
> This should be avoided due to compatibility risk, instead set `acio::ICCA_COMPAT_ACTIVE = true;` in `pcm.cpp` (like in `mga.cpp:53`)

fixed: [patch.txt](https://github.com/spice2x/spice2x.github.io/files/13930145/patch.txt)

> Should also mention that no one has the data for Charge Machine....

It might be helpful for those who have the data.

**Comment by camprevail** [comment]
Holy crap, thanks for this work. I've been messing with my charge machine all week, playing with some of these bill validator functions to get it to work right but wasn't getting very far. Just decided to dump the serial data last night and emulate that instead lol. 
The real question is, will spice2x compile for XP (probably not). If not I can at least use it for my xp build.

**Comment by camprevail** [comment]
Which I've already done, yeah. If layeredFS is still in there, it had a ton of the "safe" functions that aren't available in winxp, not to mention a couple dozen more minor changes I had to make

**Comment by camprevail** [comment]
Yeah it still throws kernel32 errors. Probably all of layeredfs needs to be removed. Anyways, I was able to build and test this on the cab with regular spice and it works great!

**Comment by smpn2** [comment]
@camprevail 
I recommend using b\*\*\*\*\*t\*\*\*\* if you are doing trial and error on a real machine. Actually I do that too.

I believe that the purpose of this pull request is to run it in a normal Windows environment.

**Comment by camprevail** [comment]
> @camprevail I recommend using b*****t**** if you are doing trial and error on a real machine. Actually I do that too.
> 
> I believe that the purpose of this pull request is to run it in a normal Windows environment.

Idk, it seems pretty conveniently timed to me asking a couple people for help finishing up this module properly. I mainly wanted it to be able to demo the machine with keypresses instead of inserting bills, but this could possibly be expanded now for more charging possibilities. 

As for the btools suggestion, it doesn't work / already tried it / not supported. I prefer to run spice on cabs whenever possible anyways, offers way more control and developer options. The whole notion that you shouldn't run spice on cabs is absurd.
